# Generated by Django 4.0.1 on 2022-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('user_id', models.IntegerField()),
                ('name', models.TextField(max_length=100, verbose_name="ім'я власника рахунку")),
                ('surname', models.TextField(max_length=100, verbose_name='прізвище власника рахунку')),
                ('patronymic', models.TextField(max_length=100, verbose_name='по-батькові власника рахунку')),
                ('iban', models.TextField(max_length=29, primary_key=True, serialize=False, unique=True, verbose_name='iban')),
                ('currency', models.TextField()),
                ('money', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='електронна адреса')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('user_id', models.IntegerField(verbose_name='id користувача')),
                ('title', models.TextField(max_length=100, verbose_name='назва картки')),
                ('account_iban', models.TextField(max_length=29, verbose_name='iban')),
                ('card_number', models.TextField(max_length=19, primary_key=True, serialize=False, unique=True, verbose_name='номер картки')),
                ('expiry_date', models.TextField(max_length=5, verbose_name='термін дії')),
                ('cvv', models.TextField(max_length=3)),
                ('cardholder_name', models.TextField(max_length=100, verbose_name="ім'я власника картки")),
                ('cardholder_surname', models.TextField(max_length=100, verbose_name='прізвище власника картки')),
                ('cardholder_email', models.EmailField(max_length=254, null=True, verbose_name='електронна адреса')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='електронна адреса')),
                ('phone_number', models.CharField(max_length=13, unique=True, verbose_name='номер телефону')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name="ім'я")),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='прізвище')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='по-батькові')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата приєднання')),
                ('is_staff', models.BooleanField(default=False, verbose_name='суперкористувач')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
