# Generated by Django 4.0.1 on 2022-04-20 17:36

import bank.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', bank.managers.UserManager()),
            ],
        ),
    ]
