# Generated by Django 4.0.1 on 2022-04-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
    ]
