# Generated by Django 4.0.1 on 2022-02-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_delete_upgradeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'Computers'), (2, 'House and Garden'), (3, 'Clothing'), (4, 'Car Products'), (5, 'Toys')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
