# Generated by Django 4.0.1 on 2022-02-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_category_alter_cart_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('computers', 'Computers'), ('house', 'House and Garden'), ('Clothing', 'Clothing'), ('car', 'Car Products'), ('clothing', 'Toys')], default=1, max_length=30),
        ),
    ]
