# Generated by Django 4.0.1 on 2022-01-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NS', 'newstories'), ('JS', 'jobstories'), ('AS', 'askstories'), ('SS', 'showstories')], default='NS', max_length=2)),
            ],
        ),
    ]
