# Generated by Django 4.0.1 on 2022-01-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_stories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySelector',
        ),
    ]
