# Generated by Django 4.0.1 on 2022-01-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_stories', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='descendants',
        ),
        migrations.RemoveField(
            model_name='new',
            name='descendants',
        ),
        migrations.RemoveField(
            model_name='show',
            name='descendants',
        ),
        migrations.AddField(
            model_name='ask',
            name='url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='ask',
            name='by',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='ask',
            name='score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ask',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='ask',
            name='time',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ask',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='ask',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='by',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='new',
            name='by',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='new',
            name='score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='new',
            name='time',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='new',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='new',
            name='url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='show',
            name='by',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='show',
            name='score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='show',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='show',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
