# Generated by Django 4.0.1 on 2022-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_stories', '0009_alter_ask_stories_id_alter_job_stories_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.RemoveField(
            model_name='new',
            name='id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='id',
        ),
        migrations.AlterField(
            model_name='ask',
            name='stories_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='stories_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='new',
            name='stories_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='stories_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
