# Generated by Django 4.0.1 on 2022-02-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_stories', '0006_remove_ask_url_ask_descendants_new_descendants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='stories_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='stories_id',
        ),
        migrations.RemoveField(
            model_name='new',
            name='stories_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='stories_id',
        ),
        migrations.AlterField(
            model_name='ask',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
